version: '3.8'
services:
  user-service: 
    build: ./user-service
    depends_on: 
      - postgres
      - auth-service
    ports: 
     - "8081:8081"
    networks:
      - app-net
  auth-service: 
    build: ./auth_service
    depends_on: 
      - postgres
    ports: 
     - "8082:8082"
    networks:
      - app-net
  task-service: 
    build: ./task-service
    depends_on: 
      - postgres
      - auth-service
      - user-service
    ports: 
     - "8083:8083"
    networks:
      - app-net    
  postgres:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net
networks:
  app-net:
    driver: bridge 
